import Head from 'next/head';
import {BsFillMoonStarsFill} from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/1655224831273.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Shantanu Swami</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className= 'bg-black px-10'>
        <section className= 'min-h-screen'>
          <nav className="py-10 mb-12 flex justify-between">
          <h1 className="font-burtons text-xl">SHANTANU SWAMI POTFOLIO</h1>
            <ul className="flex items-center"></ul>
            <h1>Developed by Shantanu with Passion</h1>
            <ul>
              <li><BsFillMoonStarsFill  className=" cursor-pointer text-2xl" /></li>
              <li><a className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#">Resume</a></li>
            </ul>

          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              SHANTANU SWAMI
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer & Designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Hi, there I am a Sophmore studying COMPUTER SCIENCE & DESIGN at Dayananda Sagar Academy of Management and Technology,
              nice to meet you, let's grow together.
            </p>
            <div className="text-5xl flex justify-center gap-5 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
            </div>
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 overflow-hidden mt-20">
              <Image src={deved} alt="for sell" layout="fill" objectFit="cover" />
            </div>
           
          </div>
        </section>
<section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Skills I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a Developer and a Designer,
              I have to done projects in
              <span className="text-teal-500"> Java, C, C++ </span>
              <span className="text-teal-500"> and Web D </span>
              and collaborated with talanted people to create a <span className="text-teal-500">
              3D FPS Game for PC  </span>
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of Skills, including Design,
              Programming, Photography, Cinematography, Editing and Teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-black flex-1">
              <Image src={design} alt="for sell" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs and Edits
              </h3>
              <p className="py-2">
                Creating elegant designs and edits as per your taste
              </p>
              <h4 className="py-4 text-teal-600">Design and Edit Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Powerdirector</p>
              <p className="text-gray-800 py-1">Lightroom</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-black flex-1">
              <Image src={code} alt="for sell" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website or any other project? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Languages I Use</h4>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">C</p>
              <p className="text-gray-800 py-1">C++</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-black flex-1">
              <Image src={consulting} alt="for sell" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Other Tools I Use</h4>
              <p className="text-gray-800 py-1">Unity 3D</p>
              <p className="text-gray-800 py-1">Unreal Engine</p>
              <p className="text-gray-800 py-1">VS Code</p>
              <p className="text-gray-800 py-1">Android Studio</p>
            </div>
          </div>
        </section>


      </main>
       
        </div>
  );
}
